# This is a basic workflow to help you get started with Actions

name: Plugin Build CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events with tags matching 'v*'
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out. 
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      # Setup Java environment. 
      - name: Setup Java environment. 
        uses: gradle/actions/setup-gradle@v3
      # Build gradle. 
      - name: Make gradle executable. 
        run: chmod +x ./gradlew   # That's not good. 
      - name: Build gradle. 
        run: ./gradlew build
      # Build plugin.
      - name: Build JAR package.
        run: ./gradlew buildPlugin
      # Generate checksum
      - name: Generate checksum
        run: |
          cd ./build/mirai/
          sha256sum ArisuBot-*.*.*.mirai2.jar > checksums.txt
      # Upload plugin.
      - name: Upload JAR package. 
        uses: actions/upload-artifact@v4
        with: 
          name: ArisuBot-Plugin
          path: |
            ./build/mirai/ArisuBot-*.*.*.mirai2.jar
            ./build/mirai/checksums.txt
      - name: Create Release.
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/mirai/ArisuBot-*.*.*.mirai2.jar
            ./build/mirai/checksums.txt
          draft: true
          token: ${{ secrets.TOKEN }}
